dest_id:
  London: '-2601889'
  New york: '20088325'
  Oxford: '-2604911'
  Paris: '-1456928'
dest_name:
  London: london
  New york: new york
  Oxford: oxford
  Paris: paris
package_name: data-tool
review_num_of_page: 5
autoencoder_n_epoch: 20
